isomerpages/pa-cdcsw

_what-we-do/For Corporates/SME Centre@Southwest.md
_what-we-do/For Environment/Sustainable South West Masterplan.md

Updated on SME contacts and Uploaded files to Environment

Updated on SME contacts and Uploaded files to Environment

---

_what-we-do/Care For The Vulnerable.md

[Update file: Care For The Vulnerable.md](https://github.com/isomerpages/pa-cdcsw/commit/6dd007a49b4cc89ee0f9d00ad33c7ec0b0537ce2)

Update file: Care For The Vulnerable.md

---

_what-we-do/For Caregivers/Caregiving @ South West.md

[Update file: Caregiving @ South West.md](https://github.com/isomerpages/pa-cdcsw/commit/7ab029e3cefa6f91eedaa83f9e44ff216c41c731)

Update file: Caregiving @ South West.md

---

_what-we-do/For Assistance/For Assistance.md

Update file: For Assistance

---

_what-we-do/For Lifelong Learning.md

Updated on SkillsFuture

---

_what-we-do/For Healthy Living/Fun Walkers @ South West.md
_what-we-do/For Healthy Living/Health Qigong @ South West.md

Updates on South West website

---

_what-we-do/For Lifelong Learning.md

Updates on SkillFuture info

---

_what-we-do/For Healthy Living/Fun Walkers @ South West.md
_what-we-do/For Healthy Living/Health Qigong @ South West.md

Updates on Qigong & Fun Walker Pages

Updates on Qigong & Fun Walker Pages

---

_about-us/About the CDC/About South West CDC.md
_about-us/About the CDC/Mission.md

Changing our mission

---

_what-we-do/For Assistance/Adopt @ South West.md

Updated on the Adopt @ SW

---

_what-we-do/For Lifelong Learning.md

Updated on Skillfuture - What we do

Updated on Skillfuture - What we do 

---

_what-we-do/For Corporates/SkillsFuture Advice For Employers.md

1. Change the entire write-up 
2. Deleted the image

SkillsFuture Advice for Employers

---

_what-we-do/For Environment/Clean Up @ South West!.md

Deleted info of the recycling info

Deleted info of the recycling info

---

index.md

Hi Yasmin,
removed additional '//' to url for tertiary grant link on homepage shortcut. hope it works.
can help to approve and see if the link is still broken?
Thanks!

Tertiary Grant Page

---

_about-us/Eco Office.md
_stories/DIY TraceTogether Pouches With Mdm Fang.md
_stories/Turning Trash Into Treasure.md
_what-we-do/For Environment/Sustainable South West Masterplan.md
_what-we-do/collection.yml

updated SW website

---

_what-we-do/For Students/South West Tertiary Grant.md

edited pchi for tertiary grant

---

_what-we-do/For Lifelong Learning.md

Hi Yasmin,
Appreciate your help to approve the removal of South West Community Job Fair EDM from the website as it has ended on Friday.
Thank you!

Remove South West Community Job Fair EDM

---

_what-we-do/For Lifelong Learning.md

Hi Yasmin,
Can help me to approve? Thank you!

Remove West Coast CC Job Fair EDM

---

_about-us/CDC Report.md
_newsroom/E BRIDGE.md

Upload the Annual Report for 2024 & BRIDGE #3

Upload the Annual Report for 2024 & BRIDGE #3

---

index.md

hi mindy i hope it works now :')

cdcv again

---

_newsroom/Media Releases.md

Hi Yasmin, can help me approve this? Thank you!

Change date for Clean Up @ SW 2025 MR

---

_what-we-do/For Caregivers/South West Caregiver Support Fund.md

Requested by Zee, updated on the changes of caregiver fund.

Updated of SW Caregiver Support Fund

---

_what-we-do/For Caregivers/South West Caregiver Support Fund.md

added in application part as per zee's request

caregiver support fund

---

_config.yml
index.md

Hi Yasmin,
Can get your help to approve the anti-scam notif? Thank you!

GOIS Anti-Scam Pop Up Notif on Website

---

_newsroom/E BRIDGE.md

Update of BRIDGE

---

_what-we-do/For Corporates/SME Centre@Southwest.md

updated info of SME
